FROM alpine:latest

RUN apk update && apk add --no-cache make

RUN mkdir /app
WORKDIR /app

COPY Makefile .

ARG TARGETARCH
COPY binaries/gozargah-node-linux-${TARGETARCH} ./main
RUN chmod +x ./main

RUN make install_xray

ENTRYPOINT ["./main", "serve"]