// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: common/service.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackendType int32

const (
	BackendType_XRAY      BackendType = 0
	BackendType_WIREGUARD BackendType = 1
)

// Enum value maps for BackendType.
var (
	BackendType_name = map[int32]string{
		0: "XRAY",
		1: "WIREGUARD",
	}
	BackendType_value = map[string]int32{
		"XRAY":      0,
		"WIREGUARD": 1,
	}
)

func (x BackendType) Enum() *BackendType {
	p := new(BackendType)
	*p = x
	return p
}

func (x BackendType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackendType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_service_proto_enumTypes[0].Descriptor()
}

func (BackendType) Type() protoreflect.EnumType {
	return &file_common_service_proto_enumTypes[0]
}

func (x BackendType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackendType.Descriptor instead.
func (BackendType) EnumDescriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{0}
}

type StatType int32

const (
	StatType_Outbounds StatType = 0
	StatType_Outbound  StatType = 1
	StatType_Inbounds  StatType = 2
	StatType_Inbound   StatType = 3
	StatType_UsersStat StatType = 4
	StatType_UserStat  StatType = 5
)

// Enum value maps for StatType.
var (
	StatType_name = map[int32]string{
		0: "Outbounds",
		1: "Outbound",
		2: "Inbounds",
		3: "Inbound",
		4: "UsersStat",
		5: "UserStat",
	}
	StatType_value = map[string]int32{
		"Outbounds": 0,
		"Outbound":  1,
		"Inbounds":  2,
		"Inbound":   3,
		"UsersStat": 4,
		"UserStat":  5,
	}
)

func (x StatType) Enum() *StatType {
	p := new(StatType)
	*p = x
	return p
}

func (x StatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_service_proto_enumTypes[1].Descriptor()
}

func (StatType) Type() protoreflect.EnumType {
	return &file_common_service_proto_enumTypes[1]
}

func (x StatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatType.Descriptor instead.
func (StatType) EnumDescriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{1}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_common_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{0}
}

// Base info response message
type BaseInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	CoreVersion   string                 `protobuf:"bytes,2,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"`
	NodeVersion   string                 `protobuf:"bytes,3,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseInfoResponse) Reset() {
	*x = BaseInfoResponse{}
	mi := &file_common_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfoResponse) ProtoMessage() {}

func (x *BaseInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfoResponse.ProtoReflect.Descriptor instead.
func (*BaseInfoResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{1}
}

func (x *BaseInfoResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *BaseInfoResponse) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *BaseInfoResponse) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

type Backend struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            BackendType            `protobuf:"varint,1,opt,name=type,proto3,enum=service.BackendType" json:"type,omitempty"`
	Config          string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Users           []*User                `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	KeepAlive       uint64                 `protobuf:"varint,4,opt,name=keep_alive,json=keepAlive,proto3" json:"keep_alive,omitempty"`
	ExcludeInbounds []string               `protobuf:"bytes,5,rep,name=exclude_inbounds,json=excludeInbounds,proto3" json:"exclude_inbounds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_common_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{2}
}

func (x *Backend) GetType() BackendType {
	if x != nil {
		return x.Type
	}
	return BackendType_XRAY
}

func (x *Backend) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *Backend) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Backend) GetKeepAlive() uint64 {
	if x != nil {
		return x.KeepAlive
	}
	return 0
}

func (x *Backend) GetExcludeInbounds() []string {
	if x != nil {
		return x.ExcludeInbounds
	}
	return nil
}

// log
type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        string                 `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_common_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{3}
}

func (x *Log) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// stats
type Stat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Link          string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Value         int64                  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stat) Reset() {
	*x = Stat{}
	mi := &file_common_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{4}
}

func (x *Stat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Stat) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Stat) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*Stat                `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_common_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{5}
}

func (x *StatResponse) GetStats() []*Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Reset_        bool                   `protobuf:"varint,2,opt,name=reset,proto3" json:"reset,omitempty"`
	Type          StatType               `protobuf:"varint,3,opt,name=type,proto3,enum=service.StatType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_common_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{6}
}

func (x *StatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatRequest) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

func (x *StatRequest) GetType() StatType {
	if x != nil {
		return x.Type
	}
	return StatType_Outbounds
}

type OnlineStatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineStatResponse) Reset() {
	*x = OnlineStatResponse{}
	mi := &file_common_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineStatResponse) ProtoMessage() {}

func (x *OnlineStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineStatResponse.ProtoReflect.Descriptor instead.
func (*OnlineStatResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{7}
}

func (x *OnlineStatResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OnlineStatResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type StatsOnlineIpListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ips           map[string]int64       `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsOnlineIpListResponse) Reset() {
	*x = StatsOnlineIpListResponse{}
	mi := &file_common_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsOnlineIpListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsOnlineIpListResponse) ProtoMessage() {}

func (x *StatsOnlineIpListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsOnlineIpListResponse.ProtoReflect.Descriptor instead.
func (*StatsOnlineIpListResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{8}
}

func (x *StatsOnlineIpListResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatsOnlineIpListResponse) GetIps() map[string]int64 {
	if x != nil {
		return x.Ips
	}
	return nil
}

type Latency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Alive         bool                   `protobuf:"varint,2,opt,name=alive,proto3" json:"alive,omitempty"`
	Delay         int64                  `protobuf:"varint,3,opt,name=delay,proto3" json:"delay,omitempty"`
	Link          string                 `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	LastSeenTime  int64                  `protobuf:"varint,5,opt,name=last_seen_time,json=lastSeenTime,proto3" json:"last_seen_time,omitempty"`
	LastTryTime   int64                  `protobuf:"varint,6,opt,name=last_try_time,json=lastTryTime,proto3" json:"last_try_time,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Latency) Reset() {
	*x = Latency{}
	mi := &file_common_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Latency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Latency) ProtoMessage() {}

func (x *Latency) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Latency.ProtoReflect.Descriptor instead.
func (*Latency) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{9}
}

func (x *Latency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Latency) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *Latency) GetDelay() int64 {
	if x != nil {
		return x.Delay
	}
	return 0
}

func (x *Latency) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Latency) GetLastSeenTime() int64 {
	if x != nil {
		return x.LastSeenTime
	}
	return 0
}

func (x *Latency) GetLastTryTime() int64 {
	if x != nil {
		return x.LastTryTime
	}
	return 0
}

func (x *Latency) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type LatencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyRequest) Reset() {
	*x = LatencyRequest{}
	mi := &file_common_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyRequest) ProtoMessage() {}

func (x *LatencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyRequest.ProtoReflect.Descriptor instead.
func (*LatencyRequest) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{10}
}

func (x *LatencyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LatencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latencies     []*Latency             `protobuf:"bytes,1,rep,name=latencies,proto3" json:"latencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyResponse) Reset() {
	*x = LatencyResponse{}
	mi := &file_common_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyResponse) ProtoMessage() {}

func (x *LatencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyResponse.ProtoReflect.Descriptor instead.
func (*LatencyResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{11}
}

func (x *LatencyResponse) GetLatencies() []*Latency {
	if x != nil {
		return x.Latencies
	}
	return nil
}

type BackendStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumGoroutine  uint32                 `protobuf:"varint,1,opt,name=num_goroutine,json=numGoroutine,proto3" json:"num_goroutine,omitempty"`
	NumGc         uint32                 `protobuf:"varint,2,opt,name=num_gc,json=numGc,proto3" json:"num_gc,omitempty"`
	Alloc         uint64                 `protobuf:"varint,3,opt,name=alloc,proto3" json:"alloc,omitempty"`
	TotalAlloc    uint64                 `protobuf:"varint,4,opt,name=total_alloc,json=totalAlloc,proto3" json:"total_alloc,omitempty"`
	Sys           uint64                 `protobuf:"varint,5,opt,name=sys,proto3" json:"sys,omitempty"`
	Mallocs       uint64                 `protobuf:"varint,6,opt,name=mallocs,proto3" json:"mallocs,omitempty"`
	Frees         uint64                 `protobuf:"varint,7,opt,name=frees,proto3" json:"frees,omitempty"`
	LiveObjects   uint64                 `protobuf:"varint,8,opt,name=live_objects,json=liveObjects,proto3" json:"live_objects,omitempty"`
	PauseTotalNs  uint64                 `protobuf:"varint,9,opt,name=pause_total_ns,json=pauseTotalNs,proto3" json:"pause_total_ns,omitempty"`
	Uptime        uint32                 `protobuf:"varint,10,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendStatsResponse) Reset() {
	*x = BackendStatsResponse{}
	mi := &file_common_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendStatsResponse) ProtoMessage() {}

func (x *BackendStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendStatsResponse.ProtoReflect.Descriptor instead.
func (*BackendStatsResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{12}
}

func (x *BackendStatsResponse) GetNumGoroutine() uint32 {
	if x != nil {
		return x.NumGoroutine
	}
	return 0
}

func (x *BackendStatsResponse) GetNumGc() uint32 {
	if x != nil {
		return x.NumGc
	}
	return 0
}

func (x *BackendStatsResponse) GetAlloc() uint64 {
	if x != nil {
		return x.Alloc
	}
	return 0
}

func (x *BackendStatsResponse) GetTotalAlloc() uint64 {
	if x != nil {
		return x.TotalAlloc
	}
	return 0
}

func (x *BackendStatsResponse) GetSys() uint64 {
	if x != nil {
		return x.Sys
	}
	return 0
}

func (x *BackendStatsResponse) GetMallocs() uint64 {
	if x != nil {
		return x.Mallocs
	}
	return 0
}

func (x *BackendStatsResponse) GetFrees() uint64 {
	if x != nil {
		return x.Frees
	}
	return 0
}

func (x *BackendStatsResponse) GetLiveObjects() uint64 {
	if x != nil {
		return x.LiveObjects
	}
	return 0
}

func (x *BackendStatsResponse) GetPauseTotalNs() uint64 {
	if x != nil {
		return x.PauseTotalNs
	}
	return 0
}

func (x *BackendStatsResponse) GetUptime() uint32 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type SystemStatsResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	MemTotal               uint64                 `protobuf:"varint,1,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	MemUsed                uint64                 `protobuf:"varint,2,opt,name=mem_used,json=memUsed,proto3" json:"mem_used,omitempty"`
	CpuCores               uint64                 `protobuf:"varint,3,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuUsage               float64                `protobuf:"fixed64,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	IncomingBandwidthSpeed uint64                 `protobuf:"varint,5,opt,name=incoming_bandwidth_speed,json=incomingBandwidthSpeed,proto3" json:"incoming_bandwidth_speed,omitempty"`
	OutgoingBandwidthSpeed uint64                 `protobuf:"varint,6,opt,name=outgoing_bandwidth_speed,json=outgoingBandwidthSpeed,proto3" json:"outgoing_bandwidth_speed,omitempty"`
	Uptime                 uint64                 `protobuf:"varint,7,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SystemStatsResponse) Reset() {
	*x = SystemStatsResponse{}
	mi := &file_common_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatsResponse) ProtoMessage() {}

func (x *SystemStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatsResponse.ProtoReflect.Descriptor instead.
func (*SystemStatsResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{13}
}

func (x *SystemStatsResponse) GetMemTotal() uint64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *SystemStatsResponse) GetMemUsed() uint64 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

func (x *SystemStatsResponse) GetCpuCores() uint64 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SystemStatsResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemStatsResponse) GetIncomingBandwidthSpeed() uint64 {
	if x != nil {
		return x.IncomingBandwidthSpeed
	}
	return 0
}

func (x *SystemStatsResponse) GetOutgoingBandwidthSpeed() uint64 {
	if x != nil {
		return x.OutgoingBandwidthSpeed
	}
	return 0
}

func (x *SystemStatsResponse) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

// User
type Vmess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vmess) Reset() {
	*x = Vmess{}
	mi := &file_common_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vmess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vmess) ProtoMessage() {}

func (x *Vmess) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vmess.ProtoReflect.Descriptor instead.
func (*Vmess) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{14}
}

func (x *Vmess) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Vless struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Flow          string                 `protobuf:"bytes,2,opt,name=flow,proto3" json:"flow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vless) Reset() {
	*x = Vless{}
	mi := &file_common_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vless) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vless) ProtoMessage() {}

func (x *Vless) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vless.ProtoReflect.Descriptor instead.
func (*Vless) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{15}
}

func (x *Vless) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vless) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

type Trojan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trojan) Reset() {
	*x = Trojan{}
	mi := &file_common_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trojan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trojan) ProtoMessage() {}

func (x *Trojan) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trojan.ProtoReflect.Descriptor instead.
func (*Trojan) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{16}
}

func (x *Trojan) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Shadowsocks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shadowsocks) Reset() {
	*x = Shadowsocks{}
	mi := &file_common_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shadowsocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shadowsocks) ProtoMessage() {}

func (x *Shadowsocks) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shadowsocks.ProtoReflect.Descriptor instead.
func (*Shadowsocks) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{17}
}

func (x *Shadowsocks) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Shadowsocks) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type Wireguard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PeerIps       []string               `protobuf:"bytes,2,rep,name=peer_ips,json=peerIps,proto3" json:"peer_ips,omitempty"`
	PreSharedKey  string                 `protobuf:"bytes,3,opt,name=pre_shared_key,json=preSharedKey,proto3" json:"pre_shared_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wireguard) Reset() {
	*x = Wireguard{}
	mi := &file_common_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wireguard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wireguard) ProtoMessage() {}

func (x *Wireguard) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wireguard.ProtoReflect.Descriptor instead.
func (*Wireguard) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{18}
}

func (x *Wireguard) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Wireguard) GetPeerIps() []string {
	if x != nil {
		return x.PeerIps
	}
	return nil
}

func (x *Wireguard) GetPreSharedKey() string {
	if x != nil {
		return x.PreSharedKey
	}
	return ""
}

type Hysteria struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          string                 `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hysteria) Reset() {
	*x = Hysteria{}
	mi := &file_common_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hysteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hysteria) ProtoMessage() {}

func (x *Hysteria) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hysteria.ProtoReflect.Descriptor instead.
func (*Hysteria) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{19}
}

func (x *Hysteria) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

type Proxy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vmess         *Vmess                 `protobuf:"bytes,1,opt,name=vmess,proto3" json:"vmess,omitempty"`
	Vless         *Vless                 `protobuf:"bytes,2,opt,name=vless,proto3" json:"vless,omitempty"`
	Trojan        *Trojan                `protobuf:"bytes,3,opt,name=trojan,proto3" json:"trojan,omitempty"`
	Shadowsocks   *Shadowsocks           `protobuf:"bytes,4,opt,name=shadowsocks,proto3" json:"shadowsocks,omitempty"`
	Wireguard     *Wireguard             `protobuf:"bytes,5,opt,name=wireguard,proto3" json:"wireguard,omitempty"`
	Hysteria      *Hysteria              `protobuf:"bytes,6,opt,name=hysteria,proto3" json:"hysteria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proxy) Reset() {
	*x = Proxy{}
	mi := &file_common_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proxy) ProtoMessage() {}

func (x *Proxy) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proxy.ProtoReflect.Descriptor instead.
func (*Proxy) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{20}
}

func (x *Proxy) GetVmess() *Vmess {
	if x != nil {
		return x.Vmess
	}
	return nil
}

func (x *Proxy) GetVless() *Vless {
	if x != nil {
		return x.Vless
	}
	return nil
}

func (x *Proxy) GetTrojan() *Trojan {
	if x != nil {
		return x.Trojan
	}
	return nil
}

func (x *Proxy) GetShadowsocks() *Shadowsocks {
	if x != nil {
		return x.Shadowsocks
	}
	return nil
}

func (x *Proxy) GetWireguard() *Wireguard {
	if x != nil {
		return x.Wireguard
	}
	return nil
}

func (x *Proxy) GetHysteria() *Hysteria {
	if x != nil {
		return x.Hysteria
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Proxies       *Proxy                 `protobuf:"bytes,2,opt,name=proxies,proto3" json:"proxies,omitempty"`
	Inbounds      []string               `protobuf:"bytes,3,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_common_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{21}
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetProxies() *Proxy {
	if x != nil {
		return x.Proxies
	}
	return nil
}

func (x *User) GetInbounds() []string {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

type Users struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Users) Reset() {
	*x = Users{}
	mi := &file_common_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{22}
}

func (x *Users) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type UsersChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Last          bool                   `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersChunk) Reset() {
	*x = UsersChunk{}
	mi := &file_common_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersChunk) ProtoMessage() {}

func (x *UsersChunk) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersChunk.ProtoReflect.Descriptor instead.
func (*UsersChunk) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{23}
}

func (x *UsersChunk) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UsersChunk) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *UsersChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

// Routing (mirrors xray app/router/command, node-friendly shapes)
type RoutingRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutboundTag   string                 `protobuf:"bytes,1,opt,name=outbound_tag,json=outboundTag,proto3" json:"outbound_tag,omitempty"`
	RuleTag       string                 `protobuf:"bytes,2,opt,name=rule_tag,json=ruleTag,proto3" json:"rule_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingRule) Reset() {
	*x = RoutingRule{}
	mi := &file_common_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingRule) ProtoMessage() {}

func (x *RoutingRule) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingRule.ProtoReflect.Descriptor instead.
func (*RoutingRule) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{24}
}

func (x *RoutingRule) GetOutboundTag() string {
	if x != nil {
		return x.OutboundTag
	}
	return ""
}

func (x *RoutingRule) GetRuleTag() string {
	if x != nil {
		return x.RuleTag
	}
	return ""
}

type RoutingRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*RoutingRule         `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingRulesResponse) Reset() {
	*x = RoutingRulesResponse{}
	mi := &file_common_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingRulesResponse) ProtoMessage() {}

func (x *RoutingRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingRulesResponse.ProtoReflect.Descriptor instead.
func (*RoutingRulesResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{25}
}

func (x *RoutingRulesResponse) GetRules() []*RoutingRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type BalancerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalancerInfoRequest) Reset() {
	*x = BalancerInfoRequest{}
	mi := &file_common_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalancerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalancerInfoRequest) ProtoMessage() {}

func (x *BalancerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalancerInfoRequest.ProtoReflect.Descriptor instead.
func (*BalancerInfoRequest) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{26}
}

func (x *BalancerInfoRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type BalancerInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OverrideTarget  string                 `protobuf:"bytes,1,opt,name=override_target,json=overrideTarget,proto3" json:"override_target,omitempty"`
	PrincipleTarget []string               `protobuf:"bytes,2,rep,name=principle_target,json=principleTarget,proto3" json:"principle_target,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BalancerInfoResponse) Reset() {
	*x = BalancerInfoResponse{}
	mi := &file_common_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalancerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalancerInfoResponse) ProtoMessage() {}

func (x *BalancerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalancerInfoResponse.ProtoReflect.Descriptor instead.
func (*BalancerInfoResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{27}
}

func (x *BalancerInfoResponse) GetOverrideTarget() string {
	if x != nil {
		return x.OverrideTarget
	}
	return ""
}

func (x *BalancerInfoResponse) GetPrincipleTarget() []string {
	if x != nil {
		return x.PrincipleTarget
	}
	return nil
}

type TestRouteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InboundTag     string                 `protobuf:"bytes,1,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	Network        string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"` // "tcp" | "udp"
	TargetIp       string                 `protobuf:"bytes,3,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	TargetDomain   string                 `protobuf:"bytes,4,opt,name=target_domain,json=targetDomain,proto3" json:"target_domain,omitempty"`
	TargetPort     uint32                 `protobuf:"varint,5,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	Protocol       string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	User           string                 `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	Attributes     map[string]string      `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FieldSelectors []string               `protobuf:"bytes,9,rep,name=field_selectors,json=fieldSelectors,proto3" json:"field_selectors,omitempty"`
	PublishResult  bool                   `protobuf:"varint,10,opt,name=publish_result,json=publishResult,proto3" json:"publish_result,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestRouteRequest) Reset() {
	*x = TestRouteRequest{}
	mi := &file_common_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRouteRequest) ProtoMessage() {}

func (x *TestRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRouteRequest.ProtoReflect.Descriptor instead.
func (*TestRouteRequest) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{28}
}

func (x *TestRouteRequest) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *TestRouteRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *TestRouteRequest) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *TestRouteRequest) GetTargetDomain() string {
	if x != nil {
		return x.TargetDomain
	}
	return ""
}

func (x *TestRouteRequest) GetTargetPort() uint32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *TestRouteRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *TestRouteRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *TestRouteRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *TestRouteRequest) GetFieldSelectors() []string {
	if x != nil {
		return x.FieldSelectors
	}
	return nil
}

func (x *TestRouteRequest) GetPublishResult() bool {
	if x != nil {
		return x.PublishResult
	}
	return false
}

type RouteResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OutboundTag       string                 `protobuf:"bytes,1,opt,name=outbound_tag,json=outboundTag,proto3" json:"outbound_tag,omitempty"`
	OutboundGroupTags []string               `protobuf:"bytes,2,rep,name=outbound_group_tags,json=outboundGroupTags,proto3" json:"outbound_group_tags,omitempty"`
	InboundTag        string                 `protobuf:"bytes,3,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	Network           string                 `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	TargetDomain      string                 `protobuf:"bytes,5,opt,name=target_domain,json=targetDomain,proto3" json:"target_domain,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RouteResult) Reset() {
	*x = RouteResult{}
	mi := &file_common_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResult) ProtoMessage() {}

func (x *RouteResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResult.ProtoReflect.Descriptor instead.
func (*RouteResult) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{29}
}

func (x *RouteResult) GetOutboundTag() string {
	if x != nil {
		return x.OutboundTag
	}
	return ""
}

func (x *RouteResult) GetOutboundGroupTags() []string {
	if x != nil {
		return x.OutboundGroupTags
	}
	return nil
}

func (x *RouteResult) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *RouteResult) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *RouteResult) GetTargetDomain() string {
	if x != nil {
		return x.TargetDomain
	}
	return ""
}

type AddRoutingRuleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Rule  string                 `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"` // JSON for one xray routing rule (same shape as routing.rules[])
	// false (default) appends the rule, keeping existing rules; true resets the
	// router (clears all rules + balancers) before adding. Default is the safe,
	// non-destructive behavior.
	ShouldReset   bool `protobuf:"varint,2,opt,name=should_reset,json=shouldReset,proto3" json:"should_reset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRoutingRuleRequest) Reset() {
	*x = AddRoutingRuleRequest{}
	mi := &file_common_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRoutingRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoutingRuleRequest) ProtoMessage() {}

func (x *AddRoutingRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoutingRuleRequest.ProtoReflect.Descriptor instead.
func (*AddRoutingRuleRequest) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{30}
}

func (x *AddRoutingRuleRequest) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *AddRoutingRuleRequest) GetShouldReset() bool {
	if x != nil {
		return x.ShouldReset
	}
	return false
}

type RemoveRoutingRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleTag       string                 `protobuf:"bytes,1,opt,name=rule_tag,json=ruleTag,proto3" json:"rule_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRoutingRuleRequest) Reset() {
	*x = RemoveRoutingRuleRequest{}
	mi := &file_common_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRoutingRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoutingRuleRequest) ProtoMessage() {}

func (x *RemoveRoutingRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoutingRuleRequest.ProtoReflect.Descriptor instead.
func (*RemoveRoutingRuleRequest) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{31}
}

func (x *RemoveRoutingRuleRequest) GetRuleTag() string {
	if x != nil {
		return x.RuleTag
	}
	return ""
}

type OverrideBalancerTargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BalancerTag   string                 `protobuf:"bytes,1,opt,name=balancer_tag,json=balancerTag,proto3" json:"balancer_tag,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverrideBalancerTargetRequest) Reset() {
	*x = OverrideBalancerTargetRequest{}
	mi := &file_common_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideBalancerTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideBalancerTargetRequest) ProtoMessage() {}

func (x *OverrideBalancerTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideBalancerTargetRequest.ProtoReflect.Descriptor instead.
func (*OverrideBalancerTargetRequest) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{32}
}

func (x *OverrideBalancerTargetRequest) GetBalancerTag() string {
	if x != nil {
		return x.BalancerTag
	}
	return ""
}

func (x *OverrideBalancerTargetRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

var File_common_service_proto protoreflect.FileDescriptor

const file_common_service_proto_rawDesc = "" +
	"\x0a\x14common/service.proto\x12\x07service\"" +
	"\x07\x0a\x05Empty\"r\x0a\x10BaseInfoResponse\x12\x18\x0a\x07" +
	"started\x18\x01 \x01(\x08R\x07started\x12!\x0a\x0ccore_v" +
	"ersion\x18\x02 \x01(\x09R\x0bcoreVersion\x12!\x0a\x0cnod" +
	"e_version\x18\x03 \x01(\x09R\x0bnodeVersion\"\xba\x01\x0a" +
	"\x07Backend\x12(\x0a\x04type\x18\x01 \x01(\x0e2\x14.service" +
	".BackendTypeR\x04type\x12\x16\x0a\x06config\x18\x02 \x01" +
	"(\x09R\x06config\x12#\x0a\x05users\x18\x03 \x03(\x0b2\x0d.serv" +
	"ice.UserR\x05users\x12\x1d\x0a\x0akeep_alive\x18\x04 " +
	"\x01(\x04R\x09keepAlive\x12)\x0a\x10exclude_inboun" +
	"ds\x18\x05 \x03(\x09R\x0fexcludeInbounds\"\x1d\x0a\x03Log" +
	"\x12\x16\x0a\x06detail\x18\x01 \x01(\x09R\x06detail\"X\x0a\x04Stat" +
	"\x12\x12\x0a\x04name\x18\x01 \x01(\x09R\x04name\x12\x12\x0a\x04type\x18\x02 \x01" +
	"(\x09R\x04type\x12\x12\x0a\x04link\x18\x03 \x01(\x09R\x04link\x12\x14\x0a\x05" +
	"value\x18\x04 \x01(\x03R\x05value\"3\x0a\x0cStatRespon" +
	"se\x12#\x0a\x05stats\x18\x01 \x03(\x0b2\x0d.service.Stat" +
	"R\x05stats\"^\x0a\x0bStatRequest\x12\x12\x0a\x04name\x18\x01" +
	" \x01(\x09R\x04name\x12\x14\x0a\x05reset\x18\x02 \x01(\x08R\x05reset" +
	"\x12%\x0a\x04type\x18\x03 \x01(\x0e2\x11.service.StatTyp" +
	"eR\x04type\">\x0a\x12OnlineStatResponse\x12\x12\x0a" +
	"\x04name\x18\x01 \x01(\x09R\x04name\x12\x14\x0a\x05value\x18\x02 \x01(\x03" +
	"R\x05value\"\xa6\x01\x0a\x19StatsOnlineIpListRes" +
	"ponse\x12\x12\x0a\x04name\x18\x01 \x01(\x09R\x04name\x12=\x0a\x03ips" +
	"\x18\x02 \x03(\x0b2+.service.StatsOnlineIpLi" +
	"stResponse.IpsEntryR\x03ips\x1a6\x0a\x08IpsE" +
	"ntry\x12\x10\x0a\x03key\x18\x01 \x01(\x09R\x03key\x12\x14\x0a\x05value\x18" +
	"\x02 \x01(\x03R\x05value:\x028\x01\"\xbf\x01\x0a\x07Latency\x12\x12\x0a\x04" +
	"name\x18\x01 \x01(\x09R\x04name\x12\x14\x0a\x05alive\x18\x02 \x01(\x08R" +
	"\x05alive\x12\x14\x0a\x05delay\x18\x03 \x01(\x03R\x05delay\x12\x12\x0a\x04" +
	"link\x18\x04 \x01(\x09R\x04link\x12$\x0a\x0elast_seen_ti" +
	"me\x18\x05 \x01(\x03R\x0clastSeenTime\x12\"\x0a\x0dlast_t" +
	"ry_time\x18\x06 \x01(\x03R\x0blastTryTime\x12\x16\x0a\x06so" +
	"urce\x18\x07 \x01(\x09R\x06source\"$\x0a\x0eLatencyReq" +
	"uest\x12\x12\x0a\x04name\x18\x01 \x01(\x09R\x04name\"A\x0a\x0fLate" +
	"ncyResponse\x12.\x0a\x09latencies\x18\x01 \x03(\x0b2\x10" +
	".service.LatencyR\x09latencies\"\xac\x02\x0a\x14" +
	"BackendStatsResponse\x12#\x0a\x0dnum_goro" +
	"utine\x18\x01 \x01(\x0dR\x0cnumGoroutine\x12\x15\x0a\x06num" +
	"_gc\x18\x02 \x01(\x0dR\x05numGc\x12\x14\x0a\x05alloc\x18\x03 \x01(\x04R" +
	"\x05alloc\x12\x1f\x0a\x0btotal_alloc\x18\x04 \x01(\x04R\x0atot" +
	"alAlloc\x12\x10\x0a\x03sys\x18\x05 \x01(\x04R\x03sys\x12\x18\x0a\x07mal" +
	"locs\x18\x06 \x01(\x04R\x07mallocs\x12\x14\x0a\x05frees\x18\x07 \x01" +
	"(\x04R\x05frees\x12!\x0a\x0clive_objects\x18\x08 \x01(\x04R" +
	"\x0bliveObjects\x12$\x0a\x0epause_total_ns\x18\x09" +
	" \x01(\x04R\x0cpauseTotalNs\x12\x16\x0a\x06uptime\x18\x0a \x01" +
	"(\x0dR\x06uptime\"\x93\x02\x0a\x13SystemStatsRespon" +
	"se\x12\x1b\x0a\x09mem_total\x18\x01 \x01(\x04R\x08memTotal\x12" +
	"\x19\x0a\x08mem_used\x18\x02 \x01(\x04R\x07memUsed\x12\x1b\x0a\x09cp" +
	"u_cores\x18\x03 \x01(\x04R\x08cpuCores\x12\x1b\x0a\x09cpu_u" +
	"sage\x18\x04 \x01(\x01R\x08cpuUsage\x128\x0a\x18incoming" +
	"_bandwidth_speed\x18\x05 \x01(\x04R\x16incoming" +
	"BandwidthSpeed\x128\x0a\x18outgoing_bandw" +
	"idth_speed\x18\x06 \x01(\x04R\x16outgoingBandwi" +
	"dthSpeed\x12\x16\x0a\x06uptime\x18\x07 \x01(\x04R\x06uptime" +
	"\"\x17\x0a\x05Vmess\x12\x0e\x0a\x02id\x18\x01 \x01(\x09R\x02id\"+\x0a\x05Vle" +
	"ss\x12\x0e\x0a\x02id\x18\x01 \x01(\x09R\x02id\x12\x12\x0a\x04flow\x18\x02 \x01(\x09" +
	"R\x04flow\"$\x0a\x06Trojan\x12\x1a\x0a\x08password\x18\x01 \x01" +
	"(\x09R\x08password\"A\x0a\x0bShadowsocks\x12\x1a\x0a\x08p" +
	"assword\x18\x01 \x01(\x09R\x08password\x12\x16\x0a\x06metho" +
	"d\x18\x02 \x01(\x09R\x06method\"k\x0a\x09Wireguard\x12\x1d\x0a\x0a" +
	"public_key\x18\x01 \x01(\x09R\x09publicKey\x12\x19\x0a\x08p" +
	"eer_ips\x18\x02 \x03(\x09R\x07peerIps\x12$\x0a\x0epre_sh" +
	"ared_key\x18\x03 \x01(\x09R\x0cpreSharedKey\"\x1e\x0a\x08" +
	"Hysteria\x12\x12\x0a\x04auth\x18\x01 \x01(\x09R\x04auth\"\x95\x02\x0a" +
	"\x05Proxy\x12$\x0a\x05vmess\x18\x01 \x01(\x0b2\x0e.service." +
	"VmessR\x05vmess\x12$\x0a\x05vless\x18\x02 \x01(\x0b2\x0e.se" +
	"rvice.VlessR\x05vless\x12'\x0a\x06trojan\x18\x03 \x01" +
	"(\x0b2\x0f.service.TrojanR\x06trojan\x126\x0a\x0bs" +
	"hadowsocks\x18\x04 \x01(\x0b2\x14.service.Shado" +
	"wsocksR\x0bshadowsocks\x120\x0a\x09wireguard" +
	"\x18\x05 \x01(\x0b2\x12.service.WireguardR\x09wire" +
	"guard\x12-\x0a\x08hysteria\x18\x06 \x01(\x0b2\x11.servic" +
	"e.HysteriaR\x08hysteria\"b\x0a\x04User\x12\x14\x0a\x05" +
	"email\x18\x01 \x01(\x09R\x05email\x12(\x0a\x07proxies\x18\x02 " +
	"\x01(\x0b2\x0e.service.ProxyR\x07proxies\x12\x1a\x0a\x08" +
	"inbounds\x18\x03 \x03(\x09R\x08inbounds\",\x0a\x05User" +
	"s\x12#\x0a\x05users\x18\x01 \x03(\x0b2\x0d.service.UserR" +
	"\x05users\"[\x0a\x0aUsersChunk\x12#\x0a\x05users\x18\x01 " +
	"\x03(\x0b2\x0d.service.UserR\x05users\x12\x14\x0a\x05ind" +
	"ex\x18\x02 \x01(\x04R\x05index\x12\x12\x0a\x04last\x18\x03 \x01(\x08R\x04l" +
	"ast\"K\x0a\x0bRoutingRule\x12!\x0a\x0coutbound_t" +
	"ag\x18\x01 \x01(\x09R\x0boutboundTag\x12\x19\x0a\x08rule_ta" +
	"g\x18\x02 \x01(\x09R\x07ruleTag\"B\x0a\x14RoutingRules" +
	"Response\x12*\x0a\x05rules\x18\x01 \x03(\x0b2\x14.servic" +
	"e.RoutingRuleR\x05rules\"'\x0a\x13Balancer" +
	"InfoRequest\x12\x10\x0a\x03tag\x18\x01 \x01(\x09R\x03tag\"j\x0a" +
	"\x14BalancerInfoResponse\x12'\x0a\x0foverrid" +
	"e_target\x18\x01 \x01(\x09R\x0eoverrideTarget\x12)" +
	"\x0a\x10principle_target\x18\x02 \x03(\x09R\x0fprinci" +
	"pleTarget\"\xba\x03\x0a\x10TestRouteRequest\x12\x1f" +
	"\x0a\x0binbound_tag\x18\x01 \x01(\x09R\x0ainboundTag\x12" +
	"\x18\x0a\x07network\x18\x02 \x01(\x09R\x07network\x12\x1b\x0a\x09tar" +
	"get_ip\x18\x03 \x01(\x09R\x08targetIp\x12#\x0a\x0dtarget" +
	"_domain\x18\x04 \x01(\x09R\x0ctargetDomain\x12\x1f\x0a\x0bt" +
	"arget_port\x18\x05 \x01(\x0dR\x0atargetPort\x12\x1a\x0a\x08" +
	"protocol\x18\x06 \x01(\x09R\x08protocol\x12\x12\x0a\x04user" +
	"\x18\x07 \x01(\x09R\x04user\x12I\x0a\x0aattributes\x18\x08 \x03(\x0b" +
	"2).service.TestRouteRequest.Attr" +
	"ibutesEntryR\x0aattributes\x12'\x0a\x0ffield" +
	"_selectors\x18\x09 \x03(\x09R\x0efieldSelectors" +
	"\x12%\x0a\x0epublish_result\x18\x0a \x01(\x08R\x0dpublis" +
	"hResult\x1a=\x0a\x0fAttributesEntry\x12\x10\x0a\x03ke" +
	"y\x18\x01 \x01(\x09R\x03key\x12\x14\x0a\x05value\x18\x02 \x01(\x09R\x05val" +
	"ue:\x028\x01\"\xc0\x01\x0a\x0bRouteResult\x12!\x0a\x0coutbou" +
	"nd_tag\x18\x01 \x01(\x09R\x0boutboundTag\x12.\x0a\x13out" +
	"bound_group_tags\x18\x02 \x03(\x09R\x11outbound" +
	"GroupTags\x12\x1f\x0a\x0binbound_tag\x18\x03 \x01(\x09R\x0a" +
	"inboundTag\x12\x18\x0a\x07network\x18\x04 \x01(\x09R\x07net" +
	"work\x12#\x0a\x0dtarget_domain\x18\x05 \x01(\x09R\x0ctar" +
	"getDomain\"N\x0a\x15AddRoutingRuleReque" +
	"st\x12\x12\x0a\x04rule\x18\x01 \x01(\x09R\x04rule\x12!\x0a\x0cshould" +
	"_reset\x18\x02 \x01(\x08R\x0bshouldReset\"5\x0a\x18Rem" +
	"oveRoutingRuleRequest\x12\x19\x0a\x08rule_ta" +
	"g\x18\x01 \x01(\x09R\x07ruleTag\"Z\x0a\x1dOverrideBala" +
	"ncerTargetRequest\x12!\x0a\x0cbalancer_ta" +
	"g\x18\x01 \x01(\x09R\x0bbalancerTag\x12\x16\x0a\x06target\x18\x02" +
	" \x01(\x09R\x06target*&\x0a\x0bBackendType\x12\x08\x0a\x04X" +
	"RAY\x10\x00\x12\x0d\x0a\x09WIREGUARD\x10\x01*_\x0a\x08StatType" +
	"\x12\x0d\x0a\x09Outbounds\x10\x00\x12\x0c\x0a\x08Outbound\x10\x01\x12\x0c\x0a" +
	"\x08Inbounds\x10\x02\x12\x0b\x0a\x07Inbound\x10\x03\x12\x0d\x0a\x09User" +
	"sStat\x10\x04\x12\x0c\x0a\x08UserStat\x10\x052\xdc\x09\x0a\x0bNodeSe" +
	"rvice\x126\x0a\x05Start\x12\x10.service.Backend" +
	"\x1a\x19.service.BaseInfoResponse\"\x00\x12(\x0a" +
	"\x04Stop\x12\x0e.service.Empty\x1a\x0e.service." +
	"Empty\"\x00\x12:\x0a\x0bGetBaseInfo\x12\x0e.service" +
	".Empty\x1a\x19.service.BaseInfoRespons" +
	"e\"\x00\x12+\x0a\x07GetLogs\x12\x0e.service.Empty\x1a\x0c" +
	".service.Log\"\x000\x01\x12@\x0a\x0eGetSystemSta" +
	"ts\x12\x0e.service.Empty\x1a\x1c.service.Sys" +
	"temStatsResponse\"\x00\x12B\x0a\x0fGetBackend" +
	"Stats\x12\x0e.service.Empty\x1a\x1d.service." +
	"BackendStatsResponse\"\x00\x129\x0a\x08GetSta" +
	"ts\x12\x14.service.StatRequest\x1a\x15.servi" +
	"ce.StatResponse\"\x00\x12J\x0a\x13GetOutbound" +
	"sLatency\x12\x17.service.LatencyReques" +
	"t\x1a\x18.service.LatencyResponse\"\x00\x12I\x0a" +
	"\x12GetUserOnlineStats\x12\x14.service.St" +
	"atRequest\x1a\x1b.service.OnlineStatRe" +
	"sponse\"\x00\x12V\x0a\x18GetUserOnlineIpListS" +
	"tats\x12\x14.service.StatRequest\x1a\".ser" +
	"vice.StatsOnlineIpListResponse\"\x00" +
	"\x12-\x0a\x08SyncUser\x12\x0d.service.User\x1a\x0e.se" +
	"rvice.Empty\"\x00(\x01\x12-\x0a\x09SyncUsers\x12\x0e.s" +
	"ervice.Users\x1a\x0e.service.Empty\"\x00\x12;" +
	"\x0a\x10SyncUsersChunked\x12\x13.service.Use" +
	"rsChunk\x1a\x0e.service.Empty\"\x00(\x01\x12C\x0a\x10L" +
	"istRoutingRules\x12\x0e.service.Empty\x1a" +
	"\x1d.service.RoutingRulesResponse\"\x00" +
	"\x12P\x0a\x0fGetBalancerInfo\x12\x1c.service.Ba" +
	"lancerInfoRequest\x1a\x1d.service.Bala" +
	"ncerInfoResponse\"\x00\x12>\x0a\x09TestRoute\x12" +
	"\x19.service.TestRouteRequest\x1a\x14.ser" +
	"vice.RouteResult\"\x00\x12B\x0a\x0eAddRouting" +
	"Rule\x12\x1e.service.AddRoutingRuleReq" +
	"uest\x1a\x0e.service.Empty\"\x00\x12H\x0a\x11Remove" +
	"RoutingRule\x12!.service.RemoveRout" +
	"ingRuleRequest\x1a\x0e.service.Empty\"\x00" +
	"\x12R\x0a\x16OverrideBalancerTarget\x12&.ser" +
	"vice.OverrideBalancerTargetReque" +
	"st\x1a\x0e.service.Empty\"\x00B#Z!github.c" +
	"om/pasarguard/node/commonb\x06proto" +
	"3"

var (
	file_common_service_proto_rawDescOnce sync.Once
	file_common_service_proto_rawDescData []byte
)

func file_common_service_proto_rawDescGZIP() []byte {
	file_common_service_proto_rawDescOnce.Do(func() {
		file_common_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_service_proto_rawDesc), len(file_common_service_proto_rawDesc)))
	})
	return file_common_service_proto_rawDescData
}

var file_common_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_service_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_common_service_proto_goTypes = []any{
	(BackendType)(0),                      // 0: service.BackendType
	(StatType)(0),                         // 1: service.StatType
	(*Empty)(nil),                         // 2: service.Empty
	(*BaseInfoResponse)(nil),              // 3: service.BaseInfoResponse
	(*Backend)(nil),                       // 4: service.Backend
	(*Log)(nil),                           // 5: service.Log
	(*Stat)(nil),                          // 6: service.Stat
	(*StatResponse)(nil),                  // 7: service.StatResponse
	(*StatRequest)(nil),                   // 8: service.StatRequest
	(*OnlineStatResponse)(nil),            // 9: service.OnlineStatResponse
	(*StatsOnlineIpListResponse)(nil),     // 10: service.StatsOnlineIpListResponse
	(*Latency)(nil),                       // 11: service.Latency
	(*LatencyRequest)(nil),                // 12: service.LatencyRequest
	(*LatencyResponse)(nil),               // 13: service.LatencyResponse
	(*BackendStatsResponse)(nil),          // 14: service.BackendStatsResponse
	(*SystemStatsResponse)(nil),           // 15: service.SystemStatsResponse
	(*Vmess)(nil),                         // 16: service.Vmess
	(*Vless)(nil),                         // 17: service.Vless
	(*Trojan)(nil),                        // 18: service.Trojan
	(*Shadowsocks)(nil),                   // 19: service.Shadowsocks
	(*Wireguard)(nil),                     // 20: service.Wireguard
	(*Hysteria)(nil),                      // 21: service.Hysteria
	(*Proxy)(nil),                         // 22: service.Proxy
	(*User)(nil),                          // 23: service.User
	(*Users)(nil),                         // 24: service.Users
	(*UsersChunk)(nil),                    // 25: service.UsersChunk
	(*RoutingRule)(nil),                   // 26: service.RoutingRule
	(*RoutingRulesResponse)(nil),          // 27: service.RoutingRulesResponse
	(*BalancerInfoRequest)(nil),           // 28: service.BalancerInfoRequest
	(*BalancerInfoResponse)(nil),          // 29: service.BalancerInfoResponse
	(*TestRouteRequest)(nil),              // 30: service.TestRouteRequest
	(*RouteResult)(nil),                   // 31: service.RouteResult
	(*AddRoutingRuleRequest)(nil),         // 32: service.AddRoutingRuleRequest
	(*RemoveRoutingRuleRequest)(nil),      // 33: service.RemoveRoutingRuleRequest
	(*OverrideBalancerTargetRequest)(nil), // 34: service.OverrideBalancerTargetRequest
	nil,                                   // 35: service.StatsOnlineIpListResponse.IpsEntry
	nil,                                   // 36: service.TestRouteRequest.AttributesEntry
}
var file_common_service_proto_depIdxs = []int32{
	0,  // 0: service.Backend.type:type_name -> service.BackendType
	23, // 1: service.Backend.users:type_name -> service.User
	6,  // 2: service.StatResponse.stats:type_name -> service.Stat
	1,  // 3: service.StatRequest.type:type_name -> service.StatType
	35, // 4: service.StatsOnlineIpListResponse.ips:type_name -> service.StatsOnlineIpListResponse.IpsEntry
	11, // 5: service.LatencyResponse.latencies:type_name -> service.Latency
	16, // 6: service.Proxy.vmess:type_name -> service.Vmess
	17, // 7: service.Proxy.vless:type_name -> service.Vless
	18, // 8: service.Proxy.trojan:type_name -> service.Trojan
	19, // 9: service.Proxy.shadowsocks:type_name -> service.Shadowsocks
	20, // 10: service.Proxy.wireguard:type_name -> service.Wireguard
	21, // 11: service.Proxy.hysteria:type_name -> service.Hysteria
	22, // 12: service.User.proxies:type_name -> service.Proxy
	23, // 13: service.Users.users:type_name -> service.User
	23, // 14: service.UsersChunk.users:type_name -> service.User
	26, // 15: service.RoutingRulesResponse.rules:type_name -> service.RoutingRule
	36, // 16: service.TestRouteRequest.attributes:type_name -> service.TestRouteRequest.AttributesEntry
	4,  // 17: service.NodeService.Start:input_type -> service.Backend
	2,  // 18: service.NodeService.Stop:input_type -> service.Empty
	2,  // 19: service.NodeService.GetBaseInfo:input_type -> service.Empty
	2,  // 20: service.NodeService.GetLogs:input_type -> service.Empty
	2,  // 21: service.NodeService.GetSystemStats:input_type -> service.Empty
	2,  // 22: service.NodeService.GetBackendStats:input_type -> service.Empty
	8,  // 23: service.NodeService.GetStats:input_type -> service.StatRequest
	12, // 24: service.NodeService.GetOutboundsLatency:input_type -> service.LatencyRequest
	8,  // 25: service.NodeService.GetUserOnlineStats:input_type -> service.StatRequest
	8,  // 26: service.NodeService.GetUserOnlineIpListStats:input_type -> service.StatRequest
	23, // 27: service.NodeService.SyncUser:input_type -> service.User
	24, // 28: service.NodeService.SyncUsers:input_type -> service.Users
	25, // 29: service.NodeService.SyncUsersChunked:input_type -> service.UsersChunk
	2,  // 30: service.NodeService.ListRoutingRules:input_type -> service.Empty
	28, // 31: service.NodeService.GetBalancerInfo:input_type -> service.BalancerInfoRequest
	30, // 32: service.NodeService.TestRoute:input_type -> service.TestRouteRequest
	32, // 33: service.NodeService.AddRoutingRule:input_type -> service.AddRoutingRuleRequest
	33, // 34: service.NodeService.RemoveRoutingRule:input_type -> service.RemoveRoutingRuleRequest
	34, // 35: service.NodeService.OverrideBalancerTarget:input_type -> service.OverrideBalancerTargetRequest
	3,  // 36: service.NodeService.Start:output_type -> service.BaseInfoResponse
	2,  // 37: service.NodeService.Stop:output_type -> service.Empty
	3,  // 38: service.NodeService.GetBaseInfo:output_type -> service.BaseInfoResponse
	5,  // 39: service.NodeService.GetLogs:output_type -> service.Log
	15, // 40: service.NodeService.GetSystemStats:output_type -> service.SystemStatsResponse
	14, // 41: service.NodeService.GetBackendStats:output_type -> service.BackendStatsResponse
	7,  // 42: service.NodeService.GetStats:output_type -> service.StatResponse
	13, // 43: service.NodeService.GetOutboundsLatency:output_type -> service.LatencyResponse
	9,  // 44: service.NodeService.GetUserOnlineStats:output_type -> service.OnlineStatResponse
	10, // 45: service.NodeService.GetUserOnlineIpListStats:output_type -> service.StatsOnlineIpListResponse
	2,  // 46: service.NodeService.SyncUser:output_type -> service.Empty
	2,  // 47: service.NodeService.SyncUsers:output_type -> service.Empty
	2,  // 48: service.NodeService.SyncUsersChunked:output_type -> service.Empty
	27, // 49: service.NodeService.ListRoutingRules:output_type -> service.RoutingRulesResponse
	29, // 50: service.NodeService.GetBalancerInfo:output_type -> service.BalancerInfoResponse
	31, // 51: service.NodeService.TestRoute:output_type -> service.RouteResult
	2,  // 52: service.NodeService.AddRoutingRule:output_type -> service.Empty
	2,  // 53: service.NodeService.RemoveRoutingRule:output_type -> service.Empty
	2,  // 54: service.NodeService.OverrideBalancerTarget:output_type -> service.Empty
	36, // [36:55] is the sub-list for method output_type
	17, // [17:36] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_common_service_proto_init() }
func file_common_service_proto_init() {
	if File_common_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_service_proto_rawDesc), len(file_common_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_service_proto_goTypes,
		DependencyIndexes: file_common_service_proto_depIdxs,
		EnumInfos:         file_common_service_proto_enumTypes,
		MessageInfos:      file_common_service_proto_msgTypes,
	}.Build()
	File_common_service_proto = out.File
	file_common_service_proto_goTypes = nil
	file_common_service_proto_depIdxs = nil
}
